#!/usr/bin/env bash

#TODO shortcut for: git remote set-url origin git@github.com:$(username)/$(reponame).git

c() { cd "$1" && ls --color=always; }
s() { sudo tee /proc/acpi/bbswitch <<<ON && startx; }

# Open pdf with zathura. You do not see the output and can close the terminal. (':' does nothing, literally)
p() { zathura "$1" &> /dev/null & :; }
PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'disown -a -h'

# Brightness settings (only use this when the normal keys don't suffice).
alias b="echo $1 > /sys/class/backlight/intel_backlight/brightness" \
      l="ls -alFh" \
      ls="ls --color=always"
