#!/usr/bin/env bash

c() { cd "$1" && ls --color=always; }

# Open pdf with zathura. 
p() { zathura "$1" &> /dev/null &! }

# Start nvidia first, then start xorg.
s() { sudo tee /proc/acpi/bbswitch <<<ON && startx; }

# Brightness settings (only use this when the normal keys don't suffice).
alias l="ls -alFh" \
      ls="ls --color=always"
      b="echo $1 > /sys/class/backlight/intel_backlight/brightness" \
