#!/usr/bin/env bash
# AUTHOR: Bram Pulles

usage ()
{
	notify-send "sxiv" "Option $1 not supported."
}

delete ()
{
	ans=$(echo -e 'n\ny' | dmenu -p "Are you sure you want to remove them?")
	[[ "$ans" != 'y' ]] && exit

	while read -r file
	do
		rm "$file"
	done
}

case "$1" in
	d) delete     ;;
	*) usage "$1" ;;
esac
