#!/usr/bin/env bash
# AUTHOR: Bram Pulles

usage ()
{
	[[ -n $1 ]] && mess="Option $1 not supported.\n"
	mess=$mess$(cat <<- EOF
		Available commands:
		  h for this help
		  d for delete
		  w for setting the wallpaper
		EOF
	)
	notify-send "sxiv" "$mess"
}

delete ()
{
	ans=$(echo -e 'n\ny' | dmenu -p "Are you sure you want to remove them?")
	[[ "$ans" != 'y' ]] && exit

	while read -r file
	do
		rm "$file"
	done
}

wallpaper ()
{
	read -r file
	setbg "$file"
}

case "$1" in
	d) delete     ;;
	w) wallpaper  ;;
	h) usage      ;;
	*) usage "$1" ;;
esac
