#!/usr/bin/env bash
# AUTHOR: Bram Pulles

# Active the gnome keyring for automatic Nextcloud authentication.
eval $(/usr/bin/gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK &

nextcloud       & # Start Nextcloud.
sxhkd           & # Start the shortcut daemon.
dunst           & # Start dunst for usage of notify-send.

xcompmgr        & # For transparency.
setbg           & # Turn on the background.
statusbar       & # Activate the statusbar for dwm.

remaps          & # Remap some keys.
unclutter       & # Cursor disappears when inactive.
touchpad-toggle & # Turn of the touchpad by default.

prime-offload   & # Load prime for GPU switching.
blueman-applet  & # Load the bluetooth applet.
check-repos all & # Check the repos for updates.

# Use the Xresources colors/settings (for sxiv).
[[ -f "$HOME"/.config/xorg/Xresources ]] && xrdb "$HOME"/.config/xorg/Xresources &
