#!/usr/bin/env bash
# AUTHOR: Bram Pulles

# Active the gnome keyring for automatic Nextcloud authentication.
eval $(/usr/bin/gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK &

nextcloud       & # Start the Nextcloud client.
sxhkd           & # Start the shortcut daemon.
dunst           & # Start dunst for usage of notify-send.
flameshot       & # Start the screenshot daemon.
blueman-applet &> /dev/null & # Start the bluetooth applet.

xcompmgr        & # For transparency.
setbg           & # Turn on the background.
statusbar       & # Activate the statusbar for dwm.

remaps          & # Remap some keys.
unclutter       & # Cursor disappears when inactive.
touchpad-toggle & # Turn of the touchpad by default.

check-repos all & # Check the repos for updates.

# Use the Xresources colors/settings (for sxiv).
[[ -f "$HOME"/.config/xorg/Xresources ]] && xrdb "$HOME"/.config/xorg/Xresources &
